### PR TITLE
Insert the fr-ca language lines and text for every menu option in app…

### PR DESCRIPTION
**Pull request by GJoubert**
…_languages.php

Insert the fr-ca language lines and text for every menu option in app_languages.php

### CODE REVIEW

**Comment by GJoubert** [comment]
The fr-ca language option was missing from the app_languages menu

**Comment by markjcrane** [comment]
Please sign up as a contributor and your changes will be accepted.
- https://github.com/fusionpbx/open-source

**Comment by markjcrane** [comment]
Maybe you missed my reply if you sign up as a contributor your pull request will be accepted.

**Comment by markjcrane** [comment]
One more attempt if you sign up as a contributor your changes will be accepted.
- https://github.com/fusionpbx/open-source

**Comment by markjcrane** [comment]
If you decide to sign up a contributor re-open the pull request.

**Pull request closed without merging**
