### PR TITLE
 Add outbound proxy to qr code

### PR DESCRIPTION
**Pull request by ewyand**
So you can set the outbound proxy from the default settings

### CODE REVIEW

**Comment by markjcrane** [comment]
This change looks like a great idea. I would prefer if you use outbound_proxy instead of out_proxy. I think its easier to know what it is by not abbreviating. If you prefer I will do it.

Second please signup as a contributor so that I can accept your change.
https://github.com/fusionpbx/open-source

**Comment by ewyand** [comment]
That makes more sense. I have made the changes.

Thanks, Erik

**Comment by ewyand** [comment]
I have signed up. I did first as profonex, but then I realized that the
commits were coming as my username ewyand. And it looks like you accepted
the ewyand because it is in the contributor's folder.

Thanks, Erik

**Comment by markjcrane** [comment]
Yes you are right about profonex becaus it was commited with a differnt user. Also does zoiper support two outbound proxies if so then its a great option for a failover. If you don't mind would be great if you look into that.

**Pull request merged**
