### PR TITLE
Domain counts accountcodes

### PR DESCRIPTION
**Pull request by konradSC**
Add the ability to view the amount of unique account codes per domain. Also adds the ability to view the number of extensions assigned to each accountcode for each domain. Results are exportable to csv.

### CODE REVIEW

**Comment by markjcrane** [comment]
Not certain if I like the name of this feature counting domains based on accountcodes. Accountcodes can be completely anything anyone wants not necessarily a domain name. Domain name for account codes is just the default that is used right now.

I would expect domain_counts to be a counting of active domains in v_domains table.

Not saying that I'm apposed to the features idea of counting unique acccountcodes. But this I would expect to be something like acccountcode_counts or maybe even just accountcodes either is more intuitively describing it.

**Comment by konradSC** [comment]
What this does addition does is let you drill down into a domain and see the unique accountcodes and how many extensions have that name. 

The idea behind this app is if you do user based billing. So if you have a per user cost of $x per user you can quickly get these numbers across all domains. If the customer requires site billing you can assign an accountcode to each extension which correlates to each site. This update lets you click on the accountcodes for a domain and see how many extensions are assigned to each site (accountcode).

**Comment by konradSC** [comment]
As an aside. This app's main feature is to give a summary of all the domains and a count of each feature. For each domain this many extensions, ring groups, devices, users, contacts, etc. That is the landing page. This update just give you the ability to drill into the information a little more.

It was helpful for my situation and I thought i'd pass it on to the community.

**Comment by markjcrane** [comment]
So in other words its goal is to duplicate the dashboard 'counts' that already exists in the dashboard.

**Comment by konradSC** [comment]
Here's the main screen:
main_app

If you click accountcodes above for a domain, it brings up a screen like this:
accountcode

I don't really like the name either. Just couldn't think of something better when i first wrote it. I'm open to suggestions. How about something dangerous sounding like app/DomainDefCon007?

**Comment by markjcrane** [comment]
Screen shot helps I'll give accept it and give it a try as time permits.

**Pull request merged**
