### PR TITLE
Add Mobile-Twinning App

### PR DESCRIPTION
**Pull request by konradSC**
This adds the mobile-twinning app.

Works like this:

Go to Apps -> Mobile Twinning. Associate the mobile number with the corresponding extension.
Go to Dialplan -> Destinations. Map a Destination to the mobile-twinning dialplan number. (*662) (spells MOB for "mobile")

You can now seamlessly move calls back and forth from your deskphone and your mobile.
If someone calls your extension and you have it forwarded (or follow-me) to your mobile, you can dial *662 from your desk to bring the call back to your desk.
If you are on your deskphone, you can dial the mobile-twinning destination (step 2), press 1 and the call is transferred to your mobile.

Notes:

This will probably not work across multiple FS servers as it is written.
This is setup for the mobile to have a 10 digit number.

Install:

On your server.
	git clone https://github.com/fusionpbx/fusionpbx-apps
Copy or move the directory 'mobile-twinning' into your main FusionPBX directory.
	cp -R fusionpbx-apps/mobile-twinning /var/www/fusionpbx/app
Move the xml dialplan file.
	cp /var/www/fusionpbx/app/mobile-twinning/390_mobile-twinning.xml /var/www/fusionpbx/app/dialplans/resources/switch/conf/dialplan/390_mobile-twinning.xml
Create the LUA script directory
	mkdir /usr/share/freeswitch/scripts/app/mobile_twinning
Copy the script
	cp /var/www/fusionpbx/app/mobile-twinning/index.lua /usr/share/freeswitch/scripts/app/mobile_twinning/index.lua
Set the permissions
	chown -R www-data:www-data /var/www/fusionpbx/app/mobile-twinning
	chown -R www-data:www-data /usr/share/freeswitch/scripts/app/mobile_twinning
	chown -R www-data:www-data /var/www/fusionpbx/app/dialplans/resources/switch/conf/dialplan

	
Log into the FusionPBX webpage
Advanced -> Upgrade
Menu Defaults and Permission Defaults.
Log out and back in

### CODE REVIEW

**Comment by stalley** [comment]
I'm unable to make this work. Several of the queries depend on the presence_id field having a value. This is not happening on forwards or follow me's.

**Comment by konradSC** [comment]
Do you have an alternate field that you would like to propose for the queries? You can uncomment line 6 in the lua script and see the queries in the logs. Run these in your sqlite instance to get a better handling of what the queries are doing.

**Comment by stalley** [comment]
I've been attempting to do that. Retrieving call from the follow me destination almost works, but the wrong call leg is retrieved. The desk phone and cell phone are bridged instead of deskphone and caller. And maybe i'm not quite clear on the instructions for 
"If you are on your deskphone, you can dial the mobile-twinning destination (step 2), press 1 and the call is transferred to your mobile."

as that doesn't seem to do anything.

**Comment by konradSC** [comment]
If it's grabbing the wrong call leg, try commenting out line 196 in the lua script. Another guy had the same issue and removing that line fixed it. I'm on master branch with FS 1.8.x. I wonder if that could be the issue. 

The 2nd half of the instructions are for transitioning from your desk phone to your mobile. 

Create a destination and set the action to this: "transfer:*662 XML yourdomain.com".

Start a call on your desk phone to someone. Next dial the destination (the new one above) from your mobile phone and press 1. It should transfer the desk phone call to your mobile.

**Comment by stalley** [comment]
That worked perfectly. I think the reason for the wrong call leg is this.
```--lookup active calls to the mobile (for follow-me)
--connect to FS database
	local dbh = Database.new('switch')
	
--check the database for the uuid of the mobile call 
	presence_id = caller_id_number.."@"..domain_name;
	call_hostname = "";
	sql = "SELECT uuid, call_uuid, hostname FROM channels ";
	sql = sql .. "WHERE callstate = 'ACTIVE' ";
	sql = sql .. "AND direction = 'outbound' ";
	sql = sql .. "AND dest = " .. mobile_twinning_number .. " ";
	sql = sql .. "AND presence_id = '" .. presence_id .. "' ";
	sql = sql .. "AND call_uuid IS NOT NULL `";````
On my system at least, there is no presence_id being set on the outbound call from the follow me so it fails this step and get's caught in the
 --lookup active calls to the mobile (for instances where the mobile switched the call from the extension) section, and so get's the bleg set.

**Pull request merged**
